// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Musiction.API.Entities;
using System;

namespace Musiction.API.Migrations
{
    [DbContext(typeof(SongContext))]
    [Migration("20181121161209_AddPresentation")]
    partial class AddPresentation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Musiction.API.Entities.Presentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Path")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Presentations");
                });

            modelBuilder.Entity("Musiction.API.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PresentationId")
                        .HasMaxLength(50);

                    b.Property<int?>("PresentationId1");

                    b.Property<string>("YouTubeUrl")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.HasIndex("PresentationId1");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Musiction.API.Entities.Song", b =>
                {
                    b.HasOne("Musiction.API.Entities.Presentation")
                        .WithMany("Songs")
                        .HasForeignKey("PresentationId1");
                });
#pragma warning restore 612, 618
        }
    }
}
