// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Musiction.API.Entities;
using System;

namespace Musiction.API.Migrations
{
    [DbContext(typeof(SongContext))]
    [Migration("20190616144231_RemoveTypeFromPresentation")]
    partial class RemoveTypeFromPresentation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Musiction.API.Entities.LinkSongToPresentation", b =>
                {
                    b.Property<int>("PresentationId");

                    b.Property<int>("SongId");

                    b.HasKey("PresentationId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("LinkSongToPresentation");
                });

            modelBuilder.Entity("Musiction.API.Entities.Presentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateBy")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("GoogleDrivePptxFileId")
                        .IsRequired();

                    b.Property<string>("GoogleDriveZipFileId");

                    b.HasKey("Id");

                    b.ToTable("Presentations");
                });

            modelBuilder.Entity("Musiction.API.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PresentationId")
                        .HasMaxLength(50);

                    b.Property<string>("YouTubeUrl")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Musiction.API.Entities.LinkSongToPresentation", b =>
                {
                    b.HasOne("Musiction.API.Entities.Presentation", "Presentation")
                        .WithMany("LinkSongToPresentation")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Musiction.API.Entities.Song", "Song")
                        .WithMany("LinkSongToPresentation")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
